# This file permits to customize, with commands,
# the menu bar of the G4UIXm, G4UIQt, G4UIWin32 sessions.
# It has no effect with G4UIterminal.

# Viewer menu :
/gui/addMenu viewer Viewer
/gui/addButton viewer "New viewer" "{gui_vis}"
/gui/addButton viewer "Set style surface" "{gui_surface}"
/gui/addButton viewer "Set style wireframe" "{gui_wireframe}"

# Custom visualisation menu
/gui/addMenu custom "Custom View"
/gui/addButton custom "Add axis" "/vis/scene/add/axes"
/gui/addButton custom "Add beam axis" "{gui_beam}"
/gui/addButton custom "Add event ID" "/vis/scene/add/eventID"
/gui/addButton custom "Add step point" "/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true"

# No hit collection is implemented
#/gui/addButton custom "Add Scorer Hits" "/vis/scene/add/psHits"
#/gui/addButton custom "Add Hits" "/vis/scene/add/hits"

# NPS tool bar
/gui/addIcon "Follow us on GitHub" user_icon "/gui/system {gui_nptool}" /home/andyb/Packages/nptool-NPTool.2.dev.Spede/NPSimulation/ressources/icons/NPToolLogo.png
/gui/addIcon "Exit" user_icon "{gui_exit}" /home/andyb/Packages/nptool-NPTool.2.dev.Spede/NPSimulation/ressources/icons/power.png
/gui/addIcon "the star gaze" user_icon "{gui_empty}" /home/andyb/Packages/nptool-NPTool.2.dev.Spede/NPSimulation/ressources/icons/empty.png 
/gui/addIcon "Update geometry" user_icon "{gui_update}" /home/andyb/Packages/nptool-NPTool.2.dev.Spede/NPSimulation/ressources/icons/recycle.png
/gui/addIcon "Save geometry to gdml" user_icon "{gui_gdml}" /home/andyb/Packages/nptool-NPTool.2.dev.Spede/NPSimulation/ressources/icons/dev.png
/gui/addIcon "Update generator" user_icon "/gen/update" /home/andyb/Packages/nptool-NPTool.2.dev.Spede/NPSimulation/ressources/icons/bolt.png
/gui/addIcon "Open generator" user_icon "/gen/open" /home/andyb/Packages/nptool-NPTool.2.dev.Spede/NPSimulation/ressources/icons/folder.png
/gui/addIcon "the moon beyond the clouds" user_icon "{gui_empty}" /home/andyb/Packages/nptool-NPTool.2.dev.Spede/NPSimulation/ressources/icons/empty.png 
/gui/addIcon "Run beam on" user_icon "/run/beamOn" /home/andyb/Packages/nptool-NPTool.2.dev.Spede/NPSimulation/ressources/icons/rocket.png
/gui/addIcon "One event" user_icon "{gui_beamon}" /home/andyb/Packages/nptool-NPTool.2.dev.Spede/NPSimulation/ressources/icons/play.png
/gui/addIcon "Activate tracking verbose" user_icon "{gui_tracking}" /home/andyb/Packages/nptool-NPTool.2.dev.Spede/NPSimulation/ressources/icons/shoeprints.png
/gui/addIcon "fill the empty dark" user_icon "{gui_empty}" /home/andyb/Packages/nptool-NPTool.2.dev.Spede/NPSimulation/ressources/icons/empty.png 
/gui/addIcon "View Browser" user_icon "{gui_browser}" /home/andyb/Packages/nptool-NPTool.2.dev.Spede/NPSimulation/ressources/icons/browser.png
/gui/addIcon "Take a screen shot" user_icon "/vis/ogl/printEPS" /home/andyb/Packages/nptool-NPTool.2.dev.Spede/NPSimulation/ressources/icons/camera.png
/gui/addIcon "Home" user_icon     "{gui_home}" /home/andyb/Packages/nptool-NPTool.2.dev.Spede/NPSimulation/ressources/icons/eye.png
/gui/addIcon "Front" user_icon    "{gui_front}" /home/andyb/Packages/nptool-NPTool.2.dev.Spede/NPSimulation/ressources/icons/arrow-up.png
/gui/addIcon "Back" user_icon     "{gui_back}" /home/andyb/Packages/nptool-NPTool.2.dev.Spede/NPSimulation/ressources/icons/arrow-down.png
/gui/addIcon "Left" user_icon     "{gui_left}" /home/andyb/Packages/nptool-NPTool.2.dev.Spede/NPSimulation/ressources/icons/arrow-left.png
/gui/addIcon "Right" user_icon    "{gui_right}" /home/andyb/Packages/nptool-NPTool.2.dev.Spede/NPSimulation/ressources/icons/arrow-right.png
/gui/addIcon "Zoom in" user_icon  "{gui_zoomin}" /home/andyb/Packages/nptool-NPTool.2.dev.Spede/NPSimulation/ressources/icons/zoomin.png
/gui/addIcon "Zoom out" user_icon "{gui_zoomout}" /home/andyb/Packages/nptool-NPTool.2.dev.Spede/NPSimulation/ressources/icons/zoomout.png
/gui/addIcon "the great void" user_icon "{gui_empty}" /home/andyb/Packages/nptool-NPTool.2.dev.Spede/NPSimulation/ressources/icons/empty.png
/gui/addIcon "Check geometry" user_icon "/geometry/test/run" /home/andyb/Packages/nptool-NPTool.2.dev.Spede/NPSimulation/ressources/icons/check.png
